---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lsprefix-edge
  template:
    metadata:
      labels:
        app: lsprefix-edge
    spec:
      containers:
        - args:
            - --v
            - "5"
            - --message-server
            - "kafka:9092"
            - --database-server
            - "http://arangodb:28529"
            - --database-name
            - "jalapeno"
            - --database-user
            - "root"
            - --database-pass
            - "jalapeno"
          image: docker.io/sbezverk/lsprefix-edge:test
          imagePullPolicy: Always
          name: lsprefix-edge
metadata:
  name: lsprefix-edge
  namespace: default
